### ISSUE TITLE
DNS解析失败，请稍后再试!

### ISSUE THREAD

**Issue by Yamds** [molanp/nonebot_plugin_mccheck#1]
![图片](https://github.com/user-attachments/assets/3eade836-c5b9-4c6c-b743-1dead099173c)
![图片](https://github.com/user-attachments/assets/6d76d5e7-882d-42c0-93a5-fd8914fd5e4e)

**Comment by molanp** [comment]
该问题为网络连接不稳定造成，请重试几次

请检查服务器是否可以访问阿里云公共DNS`223.5.5.5`和CloudFlare公共DNS`1.1.1.1`，
理论上来说，只要能访问任意一个dns就可以正常查询

如果均不可访问，请修改`utils.py`文件第285行
```py
    resolver.nameservers = ["223.5.5.5", "1.1.1.1"]
```
将其中的`223.5.5.5`或`1.1.1.1`改为你已知或当前服务商提供的DNS

**Comment by molanp** [comment]
新版本已修复
